### ISSUE TITLE
这项目很不完善

### ISSUE THREAD

**Issue by zi2ven** [MMXCawa/Python-in-Python#1]
python版本是什么，而且有以下报错
1. “sys”不是模块“os”的已知属性Pylance[reportAttributeAccessIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportAttributeAccessIssue)
2. “c”未绑定Pylance[reportUnboundVariable](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnboundVariable)

就是说，能不能改以下

**Comment by MMXCawa** [comment]
确实很不完善 因为是随便编的
我运行的版本是Python 3.12 并没有上述问题(最低运行版本是python3.8)
但是我可能知道问题出在哪并进行了修复，在几分钟后会推出更新版本：
导入了sys模块 并对字符串c进行了初始化
如果还有运行问题 请回复

**Comment by zi2ven** [comment]
> 确实很不完善 因为是随便编的 我运行的版本是Python 3.12 并没有上述问题(最低运行版本是python3.8) 但是我可能知道问题出在哪并进行了修复，在几分钟后会推出更新版本： 导入了sys模块 并对字符串c进行了初始化 如果还有运行问题 请回复

我使用了 python 3.10 版本进行运行，产生了这些错误，不过现在已经没问题了
