### ISSUE TITLE
多余的输出

### ISSUE THREAD

**Issue by zi2ven** [MMXCawa/Python-in-Python#2]
当运行某个函数，如 `print(1)` 时，会在输出的末尾添加一个 `None`

**Comment by MMXCawa** [comment]
修复了 另外问一下 是只有print函数会出现这种状况吗

**Comment by zi2ven** [comment]
> 修复了 另外问一下 是只有print函数会出现这种状况吗

任何函数

**Comment by zi2ven** [comment]
> 修复了 另外问一下 是只有print函数会出现这种状况吗

不过现在没问题了
